version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          mapping: |
            .circleci/.* circleci-changes true
          base-revision: main

          config-path: .circleci/continue_config.yml